/** Generated by `npm run cy` — source: cy_templeate.json. Re-run to refresh. */
import { VideoHeroCase1 } from "@/components/cy/HeroSection/video/videoHero_case1";
import { KeyFeatureCase1 } from "@/components/cy/KeyFeature/keyfeatureCase_1";
import { HowToStepsCase1 } from "@/components/cy/HowToSteps/how_to_steps_case1";
import { ComparisonTableCase1 } from "@/components/cy/Comparison/comparison_table_case1";
import { TestimonialGridCase3 } from "@/components/cy/UsersSay/testimonial_grid_case3";
import { PricingCase1 } from "@/components/cy/Pricing/pricing_case1";
import cyTemplate from "@/cy_templeate.json";

function cyBlockData(block: Record<string, unknown> | undefined) {
  if (!block || typeof block !== "object" || Array.isArray(block)) return {};
  const o: Record<string, unknown> = { ...block };
  for (const k of Object.keys(o)) {
    if (k.startsWith("__")) delete o[k];
  }
  if ("_meta" in o) delete o._meta;
  return o;
}

export default function Page() {
  return (
    <>
      <VideoHeroCase1 data={cyBlockData(cyTemplate["VideoHeroCase1"] as Record<string, unknown>) as never} />
      <KeyFeatureCase1 data={cyBlockData(cyTemplate["KeyFeatureCase1"] as Record<string, unknown>) as never} />
      <HowToStepsCase1 data={cyBlockData(cyTemplate["HowToStepsCase1"] as Record<string, unknown>) as never} />
      <ComparisonTableCase1 data={cyBlockData(cyTemplate["ComparisonTableCase1"] as Record<string, unknown>) as never} />
      <TestimonialGridCase3 data={cyBlockData(cyTemplate["TestimonialGridCase3"] as Record<string, unknown>) as never} />
      <PricingCase1 data={cyBlockData(cyTemplate["PricingCase1"] as Record<string, unknown>) as never} />
    </>
  );
}
