/** Generated by `npm run cy` — source: cy_templeate.json. Re-run to refresh. */
import PricingSection from "@/components/PricingSection";
import { VideoHeroCase1 } from "@/components/cy/HeroSection/video/videoHero_case1";
import { KeyFeatureCase1 } from "@/components/cy/KeyFeature/keyfeatureCase_1";
import { HowToStepsCase1 } from "@/components/cy/HowToSteps/how_to_steps_case1";
import { ComparisonTableCase1 } from "@/components/cy/Comparison/comparison_table_case1";
import { TestimonialGridCase3 } from "@/components/cy/UsersSay/testimonial_grid_case3";
import { FaqCase1 } from "@/components/cy/FAQ/faq_case1";
import cyTemplate from "@/cy_templeate.json";

function cyBlockData(block: Record<string, unknown> | undefined) {
  if (!block || typeof block !== "object" || Array.isArray(block)) return {};
  const o: Record<string, unknown> = { ...block };
  for (const k of Object.keys(o)) {
    if (k.startsWith("__")) delete o[k];
  }
  if ("_meta" in o) delete o._meta;
  return o;
}

export default function Page() {
  return (
    <>
      <VideoHeroCase1 data={cyBlockData(cyTemplate["VideoHeroCase1"] as Record<string, unknown>) as never} />
      <KeyFeatureCase1 data={cyBlockData(cyTemplate["KeyFeatureCase1"] as Record<string, unknown>) as never} />
      <HowToStepsCase1 data={cyBlockData(cyTemplate["HowToStepsCase1"] as Record<string, unknown>) as never} />
      <ComparisonTableCase1 data={cyBlockData(cyTemplate["ComparisonTableCase1"] as Record<string, unknown>) as never} />
      <TestimonialGridCase3 data={cyBlockData(cyTemplate["TestimonialGridCase3"] as Record<string, unknown>) as never} />
      <section id="pricing" className="bg-background px-4 py-24">
        <div className="mx-auto max-w-7xl">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-4xl font-bold text-foreground md:text-5xl">
              Choose Your Perfect Plan
            </h2>
            <p className="mx-auto max-w-2xl text-xl text-muted-foreground">
              All plans include HD download and fast AI generation.
            </p>
          </div>
          <PricingSection hideSection hideHeader />
        </div>
      </section>
      <FaqCase1 data={cyBlockData(cyTemplate["FaqCase1"] as Record<string, unknown>) as never} />
    </>
  );
}
